server:
  port: 8083
spring:
  application:
    name: LoginSpringBootThymeleaf
  flyway:
    enabled: true
    
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/${MYSQL_DB:LoginSpringBootThymeleaf}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    
  jpa:
    hibernate:
      ddl-auto: none
      
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB