CREATE TABLE TB_USUARIO(
   ID_USUARIO INT NOT NULL AUTO_INCREMENT,
   DS_NOME VARCHAR (60) NOT NULL,
   DS_LOGIN VARCHAR (60) NOT NULL,
   DS_SENHA VARCHAR (400) NOT NULL,
   FL_ATIVO NUMERIC(10) NOT NULL,
   PRIMARY KEY (ID_USUARIO)
);