CREATE TABLE TB_PERMISSAO_GRUPO
(
   ID_PERMISSAO INT NOT NULL,
   ID_GRUPO INT NOT NULL,
   CONSTRAINT PK_PER_GRUP PRIMARY KEY
   (
      ID_PERMISSAO,
      ID_GRUPO
   ),
   CONSTRAINT FK_PERM_1 FOREIGN KEY (ID_PERMISSAO) REFERENCES TB_PERMISSAO (ID_PERMISSAO),
   CONSTRAINT FK_GRUP_1 FOREIGN KEY (ID_GRUPO) REFERENCES TB_GRUPO (ID_GRUPO)
);