CREATE TABLE TB_USUARIO_GRUPO(
  ID_USUARIO INT NOT NULL,  
  ID_GRUPO   INT NOT NULL,
  CONSTRAINT PK_USU_GRUP   PRIMARY KEY(ID_USUARIO,ID_GRUPO),
  FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO), 
  FOREIGN KEY(ID_GRUPO)  REFERENCES TB_GRUPO(ID_GRUPO)
);